@startuml
skinparam componentStyle rectangle

component "Основная система" as main_system

together {
  component "Модуль А" as module_a
  component "Модуль Б" as module_b
}

main_system --> module_a
main_system --> module_b
@enduml

@startuml
skinparam componentStyle rectangle

component "Клиентское приложение" as client

together {
  component "API Gateway" as api
  component "База данных" as db
}

together {
  component "API Gateway" as api1
  component "База данных" as db1
}
component "Аналитическая система" as analytics

component "Аналитическая система" as analytics1

client --> api 
client --> db 
api --> analytics : Логи
db --> analytics : Метрики
analytics --> analytics1
analytics1-->api1
analytics1-->db1

@enduml