@startuml

class IEntity<interface>{
    GetGUID(): GUID;
}

class Person{
    m_name : string;
    m_password:string;
    m_chats: vedtor<GUID>;
}

class Chat{
    m_name : string;
    m_participants: vector<GUID>
    m_messages: vector<Message>
}


class Message{
    m_user: GUID;
    m_text: string;
}

IEntity <|.. Person
IEntity <|.. Chat
Chat ..> Message : contains
Chat ..> Person : m_participants
Person ..> Chat : m_chats

@enduml